package sk.martinliptak.ita.mapper;

import org.junit.jupiter.api.Test;
import org.mapstruct.factory.Mappers;
import sk.martinliptak.ita.domain.Product;
import sk.martinliptak.ita.model.CreateProductRequestDto;
import sk.martinliptak.ita.model.ProductDto;


import static org.assertj.core.api.Assertions.*;
import static sk.martinliptak.ita.mapper.ProductAssertions.assertFieldsEquality;
import static sk.martinliptak.ita.mother.ProductMother.*;

class ProductMapperTest {
    private final ProductMapper productMapper = Mappers.getMapper(ProductMapper.class);

    @Test
    void toDto() {
        Product source = prepareProduct();
        ProductDto expectedResult = prepareProductDto();
        ProductDto result = productMapper.toDto(source);

        assertThat(result.getId()).isEqualTo(source.getId());
        assertFieldsEquality(result, expectedResult);
    }

    @Test
    void toDomain() {
        CreateProductRequestDto source = prepareCreateProductDto();
        Product expectedResult = prepareProduct();
        Product result = productMapper.toDomain(source);

        assertThat(result.getId()).isNull(); // ID will be generated by JPA
        assertFieldsEquality(result, expectedResult);
    }

    @Test
    void mergeProduct() {
        CreateProductRequestDto source = prepareCreateProductDto2(); // A different dto
        Product target = prepareProduct(); // Being updated (Becomes result after merge)
        Product expectedResult = prepareProduct2(); // Expected

        productMapper.mergeProduct(target, source);

        assertThat(target.getId()).isEqualTo(target.getId()); // Because ID cannot change
        assertFieldsEquality(target, expectedResult);
    }
}