create table author
(
    id          int8 generated by default as identity,
    created_at  timestamp,
    modified_at timestamp,
    bio         varchar(255),
    birth_date  date,
    name        varchar(255),
    primary key (id)
);
create table cart
(
    id          int8 generated by default as identity,
    created_at  timestamp,
    modified_at timestamp,
    primary key (id)
);
create table cart_products
(
    cart_id     int8 not null,
    products_id int8 not null,
    primary key (cart_id, products_id)
);
create table eshop_order
(
    id          int8 generated by default as identity,
    created_at  timestamp,
    modified_at timestamp,
    status      varchar(255),
    primary key (id)
);
create table eshop_order_products
(
    order_id    int8 not null,
    products_id int8 not null,
    primary key (order_id, products_id)
);
create table genre
(
    id          int8 generated by default as identity,
    created_at  timestamp,
    modified_at timestamp,
    description varchar(255),
    name        varchar(255),
    primary key (id)
);
create table product
(
    id          int8 generated by default as identity,
    created_at  timestamp,
    modified_at timestamp,
    description varchar(512),
    image       varchar(255),
    name        varchar(255),
    price       int8,
    stock       int8,
    author_id   int8,
    genre_id    int8,
    primary key (id)
);
alter table if exists cart_products
    add constraint fk_product_id foreign key (products_id) references product;
alter table if exists cart_products
    add constraint fk_cart_id foreign key (cart_id) references cart;
alter table if exists eshop_order_products
    add constraint fk_products_id foreign key (products_id) references product;
alter table if exists eshop_order_products
    add constraint fk_eshop_order_id foreign key (order_id) references eshop_order;
alter table if exists product
    add constraint fk_author_id foreign key (author_id) references author;
alter table if exists product
    add constraint fk_genre_id foreign key (genre_id) references genre;